// <auto-generated />
namespace login11.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class loginattempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginattempt));
        
        string IMigrationMetadata.Id
        {
            get { return "202409251320291_loginattempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
